Added the volunteers page.
PyConPune/pune.pycon.org pull request #21
Opened 2016-11-17 14:25 UTC by amolkahat

Hi Sayan I created the page. Please give review on this.

2016-11-18 21:17 UTC, amolkahat commented
@sayanchowdhury please take a look. I fixed volunteers page.

2016-11-19 15:57 UTC, sayanchowdhury commented
The page needs to be based on the base/base_ot.html template. Check the structure of the registration template

2016-11-19 15:57 UTC, sayanchowdhury requested changes

2016-11-19 15:57 UTC, sayanchowdhury commented on css/main.css
> -  text-transform: none;
Why remove this?

2016-11-24 14:43 UTC, amolkahat commented
@sayanchowdhury Plaease take a look.

2016-11-26 15:05 UTC, sayanchowdhury commented
How are you testing the pages?

2017-07-09 09:55 UTC, closed without merging