Add basic celery-rabbitmq structure
PyConPune/pune.pycon.org pull request #60
Opened 2017-07-18 14:11 UTC by vivekanand1101

Signed-off-by: Vivek Anand <vivekanand1101@gmail.com>

2017-07-18 18:52 UTC, sayanchowdhury commented on pyconpune/tasks.py
> +if os.environ.get('CELERY_BROKER_URL'):
Can we push this to the settings file?

2017-07-25 06:55 UTC, sayanchowdhury requested changes

2017-07-25 06:55 UTC, sayanchowdhury commented on pyconpune/tasks.py
> +import settings
You need to import from django.conf rather than just importing settings

2017-07-25 06:55 UTC, sayanchowdhury commented on pyconpune/tasks.py
> +    print 'Sending mails bro'
This method should be created as a utility method.

2017-07-25 06:55 UTC, sayanchowdhury commented on pyconpune/tasks.py
> +    broker_url = 'amqp://localhost:5672'
We should not hard-code URL, raise an error if the BROKER URL is not set

2017-07-25 06:55 UTC, sayanchowdhury commented on pyconpune/tasks.py
> +from celery import Celery
The `pyconpune/tasks.py` file should move into `root`.

2017-07-25 06:55 UTC, sayanchowdhury commented on runworker.py
> +    Code taken from https://pagure.io/pagure/blob/master/f/runworker.py
This file needs to be created as a django management command.

2017-07-25 06:55 UTC, sayanchowdhury commented on pyconpune/settings/__init__.py
> +CELERY_BROKER_URL = None
Why not set the development URL here itself.

2017-07-25 07:23 UTC, vivekanand1101 commented on pyconpune/tasks.py
> +    broker_url = 'amqp://localhost:5672'
That was for development, if anyone is feeling lazy

2017-09-15 06:34 UTC, closed without merging

2017-09-15 06:43 UTC, vivekanand1101 commented
This. This PR. This is one of the saddest thing that has ever happened to me.