Update readme with development setup instructions
PyConPune/pune.pycon.org pull request #63
Opened 2017-07-23 08:37 UTC by mbtamuli

Fix for issue #62

2017-07-25 06:49 UTC, sayanchowdhury requested changes

2017-07-25 06:49 UTC, sayanchowdhury commented on README.md
> +git checkout feature/django
You need to pull the branch before checkout

2017-07-25 06:49 UTC, sayanchowdhury commented on README.md
> +4. To start working you need to check out the development branch,
Remove the trailing comma

2017-07-25 06:56 UTC, sayanchowdhury commented
The PR should be to merge into 2018 branch and not feature/django branch.

2017-07-26 13:33 UTC, sayanchowdhury commented
@mbtamuli You need to write the code on top of 2018 branch, right now you checked out your code out of feature/django branch

2017-07-26 15:53 UTC, mbtamuli commented
Okay. Will update.

2017-07-26 21:24 UTC, mbtamuli commented on README.md
> +git checkout feature/django
Done

2017-07-31 08:19 UTC, sayanchowdhury commented on README.md
> +git pull
Should it be `git pull` or `git fetch`?

2017-08-01 15:50 UTC, mbtamuli commented on README.md
> +git pull
Okay

2017-08-04 10:00 UTC, merged